services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  OliverKroener\OkAiWriter\:
    resource: '../Classes/*'

  OliverKroener\OkAiWriter\Controller\AiTextController:
    public: true

  OliverKroener\OkAiWriter\Controller\Backend\ConfigurationController:
    public: true

  OliverKroener\OkAiWriter\Service\ConfigurationService:
    public: true
